# Generated by Django 5.0.3 on 2024-03-06 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(db_column='client_ID', max_length=256, primary_key=True, serialize=False)),
                ('nom_client', models.CharField(blank=True, max_length=256, null=True)),
                ('categorie_client', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('ville_id', models.IntegerField(db_column='ville_ID', primary_key=True, serialize=False)),
                ('ville', models.CharField(blank=True, max_length=256, null=True)),
                ('etat', models.CharField(blank=True, max_length=256, null=True)),
                ('pays', models.CharField(blank=True, max_length=256, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=256, null=True)),
                ('marche', models.CharField(blank=True, max_length=256, null=True)),
                ('region', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'localisation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('produit_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=256, null=True)),
                ('sous_category', models.CharField(blank=True, db_column='sous_Category', max_length=256, null=True)),
                ('nom_produit', models.CharField(blank=True, max_length=256, null=True)),
                ('produit_priority', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('date_id', models.CharField(db_column='date_ID', max_length=512, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('jour', models.IntegerField(blank=True, null=True)),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeExpedition',
            fields=[
                ('expedition_id', models.CharField(db_column='expedition_ID', max_length=256, primary_key=True, serialize=False)),
                ('mode_expidition', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'type_expedition',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('ville', models.OneToOneField(db_column='ville_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.localisation')),
                ('produit_id', models.CharField(max_length=200)),
                ('cout_expedition', models.IntegerField(blank=True, db_column='cout_Expedition', null=True)),
            ],
            options={
                'db_table': 'expedition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('date', models.OneToOneField(db_column='date_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.time')),
                ('retour_quantity', models.IntegerField(blank=True, db_column='retour_Quantity', null=True)),
            ],
            options={
                'db_table': 'retour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('date', models.OneToOneField(db_column='date_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.time')),
                ('prix_ventes', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('reduction', models.IntegerField(blank=True, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ventes',
                'managed': False,
            },
        ),
    ]
