# Generated by Django 5.0.3 on 2024-03-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_client_localisation_produit_time_typeexpedition_and_more'),
    ]

    operations = [
    ]
